name: KioCG-ShopAddon
main: com.kiocg.ShopAddon.ShopAddon
version: 2021
api-version: 1.16

depend: [ "QuickShop" ]

permissions:
  kiocg.shopitemonly.bypass:
    description: 绕过商店物品限制
    default: op
