name: KioCG-LittleThings
main: com.kiocg.LittleThings.LittleThings
version: 2021
api-version: 1.16

softdepend: [ "KioCG-qqBot" ]

permissions:
  kiocg.vanishingcurse.keep:
    description: "死亡保留消失诅咒的物品"
    default: false
  kiocg.catchmonsters.use:
    description: "允许下届之星捕捉怪物"
    default: true
  kiocg.originrespawn.bypass:
    description: "绕过死亡原地复活"
    default: false
  kiocg.littlethings.at:
    description: "允许@玩家"
    default: true
  kiocg.littlethings.fastworkbench:
    description: "允许使用随身工作台"
    default: op
  kiocg.cancelspawnerplace.bypass:
    description: "绕过禁止放置刷怪笼限制"
    default: op
