name: KioCG-LittleThings
main: com.kiocg.LittleThings.LittleThings
version: 2021
api-version: 1.16

softdepend: [ "KioCG-qqBot" ]

commands:
  back:
    description: "代替/back指令."
    permission: kiocg.command.back
    permission-message: "§a[§b豆渣子§a] §c这个指令不可以喔 qaq"
    usage: "§a[§b豆渣子§a] §6请使用磁石指针传送功能代替/back指令."
  sethome:
    description: "代替/sethome指令."
    permission: kiocg.command.sethome
    permission-message: "§a[§b豆渣子§a] §c这个指令不可以喔 qaq"
    usage: "§a[§b豆渣子§a] §6请使用磁石指针传送功能代替/sethome指令."

permissions:
  kiocg.command.back:
    description: 代替/back指令
    default: true
  kiocg.command.sethome:
    description: 代替/sethome指令
    default: true

  kiocg.vanishingcurse.keep:
    description: "死亡保留消失诅咒的物品"
    default: false
  kiocg.catchmonsters.use:
    description: "允许下届之星捕捉怪物"
    default: true
  kiocg.originrespawn.bypass:
    description: "绕过死亡原地复活"
    default: false
  kiocg.littlethings.at:
    description: "允许@玩家"
    default: true
  kiocg.littlethings.fastworkbench:
    description: "允许使用随身工作台"
    default: op
  kiocg.cancelspawnerplace.bypass:
    description: "绕过禁止放置刷怪笼限制"
    default: op
