name: qqBot
main: com.kiocg.qqBot.qqBot
version: 2021
api-version: 1.16

commands:
  qqbot:
    description: "重载配置文件"
    permission: kiocg.command.qqbot
    permission-message: "§a[§b豆渣子§a] §c这个指令不可以喔 qaq"
    usage: "用法: /<command> 重载配置文件."
