name: AntiCheatingClient
main: com.kiocg.java.AntiCheatingClient
version: 2021
api-version: 1.16

softdepend: [ "qqBot" ]

permissions:
  kiocg.anticheatingclient.bypass:
    description: 绕过反作弊验证
    default: op
