name: KioCG-AntiCheatingClient
main: com.kiocg.AntiCheatingClient.AntiCheatingClient
version: 2021
api-version: 1.17

softdepend: [ "KioCG-qqBot" ]

permissions:
  kiocg.anticheatingclient.bypass:
    description: 绕过反作弊验证
    default: op
