name: FoodFlight
main: com.kiocg.FoodFlight.FoodFlight
version: 2021
api-version: 1.16

commands:
  fly:
    description: "切换飞行模式."
    permission: kiocg.command.fly
    permission-message: "§a[§b豆渣子§a] §c这个指令不可以喔 qaq"
    usage: "用法: /<command> 切换飞行模式."

permissions:
  kiocg.command.fly:
    description: 切换飞行模式
    default: true

  kiocg.foodflight.world_name:
    description: 允许在指定世界飞行
    default: op
  kiocg.foodflight.free.world_name:
    description: 允许在指定世界无限飞行
    default: op
  kiocg.foodflight.free:
    description: 允许在所有世界无限飞行
    default: op
